[package]
name = "gig-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "gig"
path = "src/main.rs"

[dependencies]
gig-core = { path = "../gig-core" }
gig-gui = { path = "../gig-gui" }
clap = { workspace = true }
clap_complete = { workspace = true }
comfy-table = { workspace = true }
owo-colors = { workspace = true }
time = { workspace = true }
rusqlite = { workspace = true }
arboard = { workspace = true }
serde_json = "1"

[dev-dependencies]
zip = { workspace = true }
